# Generated by Django 4.0.6 on 2022-10-05 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictimg',
            name='predictImg',
        ),
        migrations.AddField(
            model_name='predictimg',
            name='userImg',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictimg',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
