# Generated by Django 4.0.6 on 2022-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp2', '0003_remove_predictimg_name_predictimg_leafname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictimg',
            name='LeafName',
            field=models.CharField(choices=[('apple.h5', 'apple'), ('2', 'blueberry'), ('3', 'cherry'), ('4', 'corn'), ('5', 'grape'), ('6', 'orange'), ('7', 'peach'), ('8', 'pepper'), ('9', 'potato'), ('10', 'raspberry'), ('11', 'soybean')], max_length=20),
        ),
    ]
