# Generated by Django 4.0.6 on 2022-10-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp2', '0004_alter_predictimg_leafname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictimg',
            name='LeafName',
            field=models.CharField(choices=[('apple.h5', 'apple'), ('blueberry.h5', 'blueberry'), ('cherry.h5', 'cherry'), ('corn.h5', 'corn'), ('grape.h5', 'grape'), ('orange.h5', 'orange'), ('peach.h5', 'peach'), ('pepper.h5', 'pepper'), ('potato.h5', 'potato'), ('raspberry.h5', 'raspberry'), ('soybean.h5', 'soybean'), ('squash.h5', 'squash'), ('strawberry.h5', 'strawberry')], max_length=20),
        ),
    ]
